language: android

android:
  components:
    # Update tools and then platform-tools explicitly so lint gets an updated database. Can be removed once 3.0 is out.
    - tools
    - platform-tools

jdk:
  - oraclejdk8

env:
  global:
     - secure: "KnBWcdEJkNRFGomE59OIbUNUtg7/veMQ3Hk3NQfSTLIAIR7kz+MAxWpGKPzadAn5Zfnjj1wMU5HdE9ZxV8djoxKfjxBDD4BkucOThB9xurdn7qWvVK6h1iAsFqwYL2Z95hK8cFkr/bvvR1MX+Fb5JB4qKExNkcRcZWuholYQTo67mU8JaxdodAKMOS9O2SQMgDn2jbzm1aLN17ADxzmmYpxk2zays9JEOaIFNWoGQzlqiWN2sHOS3k4nJxUwIu+gxJ/m6JnVpuCcVn7rqTw0dNtSihu2c1dqr6N/dSzuy/EYqOBACoS7Ufn84sikJwjJBLUNBI1Nv53s1kjCtv560zPwDvhFXTUCL2aMdbGXEemG5BwqvSq782X8J/ctLHS/fMh1g//nczodbcn190k9m+SCHIsg5CeiswIP1m8bGKFhB+9kjtpCGIzOWHeKeWSp2UTmyR4dsumdvdhyZafG9UYDuvulhq5SVLmIi1NyvVrbxHQpfvblrHJFGGss2zALRtMX1D43gN0JSuhv/NV7zK/7kQ2lZ5pYZj+TjzPNqkM9CybVy7pdPTo7WPplmCmMPfpJ2+tBbMdvQcqO3pgV92cCJuX/uNcfoq+aNEqceW+lRnX0zuMabxOAn9HKCSNs9DZNQ+cMBCIdCmyioucwv9NJxLtzb1hNFD+M27Jen6E="
     - secure: "rfQHWGI1VR6ezW8c9UmKCWwkAgtngO4ppjfQA+s6zdDOBQ1SYx3kC33qbTzfUxuXrmzumMNlGrIMxF3z+jGGvkGGReHFD0xL4gOZj8u9F/6pi1Yr7stGpNbW9r7P4jo3n2T9f+s1mWZn3A3zONwtZd+IuowlVdnFSMfi43oS00+1CRPBGXKUn5OH8XDfxnSXLiMmjVguZYNca2Pt1JQnUKLWIDuLwZlpXwAvI89ADbnHw6mK1Cea0H/ExrEs4NEHaaPJppr150X2TNqcY5OxGg8KtLpzhDf8fSIiRf1ZnM64lI0L+QoWlz1m2QTb+YGg00vDbJmX2Uo1FqDff9tD6Zn51auEngP6LlysqF6YVKPpw5/EFu/IRp72V5nJq+nucw6FR5+OqWQaKwbZNoPH183WcsBkoTnEnrj4Y/+PsjSXl8GmndMSOcOhdjGVJdfreSbdxip/+CULzw1ljkQKtPNw4skedu0NexJj14fmHhPrkCh0JZOxB3VusmWzmxkOyAUToWNA9I+FB7tcqrU+5IGiNLtjumT18o7sWquLXBdW50cOc4pOyyZuVlU/apad/4I6xrOpJPqnVF/f1Hkp+S3KkAzvmaxjvUCXgB1jN3AUZr/sntuBmptD+6NF61+V7Ed9bJlE6JXAz0fGz877Wzu+qAbIddTE7lfAPrXbWQ8="

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools
  - sdkmanager emulator
  # Install the system image
  - sdkmanager "system-images;android-22;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n nexus5 -k "system-images;android-22;default;armeabi-v7a" --device "Nexus 5"
  - $ANDROID_HOME/emulator/emulator -avd nexus5 -cores 1 -gpu swiftshader -no-audio -no-window -skin 1080x1920 &

install: ./gradlew clean assemble assembleAndroidTest --stacktrace


before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script: ./gradlew check connectedCheck --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

